# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSArDNFm4IMrnhlGScUd56ytjfso4FYX
"""

import numpy as np
import matplotlib.pyplot as plt

# X qiymatlari
x = np.linspace(0, 10, 100)
# Y qiymatlari
y = np.sin(x)

# Grafikni chizish
plt.plot(x, y, label="Sinus(x)", color="blue")


plt.title("Sinus Funktsiyasining Grafiki")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")

# To'rlarni qo'shish
plt.grid(True)

# Legenda qo'shish
plt.legend()

# Grafikni ko'rsatish
plt.show()

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(42)
x = np.random.uniform(0, 10, 50)
y = np.random.uniform(0, 10, 50)

plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='blue', label='Nuqtalar')

plt.title('Tasodifiy Nuqtalar Scatter Grafiki', fontsize=14)
plt.xlabel('X qiymatlari', fontsize=12)
plt.ylabel('Y qiymatlari', fontsize=12)
plt.legend()
plt.grid(True)
plt.show()

import pandas as pd

# Read the CSV file
file_path = "/content/WHO COVID-19 cases.csv"  # Replace with your file path
data = pd.read_csv(file_path)

# Filter data for a specific country, e.g., 'Afghanistan'
country = 'Afghanistan'  # Replace with the desired country name
country_data = data[data['Country'] == country]  # Replace 'Country' with your actual column name

# Display the filtered data
print(f"Data for {country}:")
print(country_data)

# Save the filtered data to a new CSV file
country_data.to_csv(f"{country}_data.csv", index=False)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('/content/sample_data/5440806137998990582.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('/content/sample_data/5393468752219199572.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('/content/5307905285626652659.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)